[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
hcl-rs = "0.18.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml_ng = "0.10.0"
toml = "0.8.19"
