declare_fns!(default.ctx,
    FN_VEC => "s",
    FN_JOIN => "join",
    FN_RANGE => "range",
    FN_MERGE => "merge",
    FN_SPLIT => "split",
    FN_FORMAT => "format",
    FN_CONCAT => "concat",
    FN_LENGTH => "length",
    FN_UNIQUE => "unique",
    FN_COMPACT => "compact",
    FN_TYPE_OF => "type_of",
    FN_REVERSE => "reverse",
    FN_FLATTEN => "flatten",
    FN_CONTAINS => "contains"
);
